worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080

# change to URI of your postgres database
pg-connection: postgresql://vcm:nu1ostaFor@postgres:5432/lab_db